HTTP/1.0 200 OK
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>Disculpe las molestias</h1>
<p>Estamos haciendo nuestro mejor esfuerzo para estar disponibles nuevamente</p>
</body></html>
